_format_version: "3.0"
plugins:
  - config:
      credentials: true
      exposed_headers: null
      headers: null
      max_age: null
      methods:
        - GET
        - PUT
        - POST
        - DELETE
      origins:
        - '*'
      preflight_continue: false
    enabled: true
    name: cors
    protocols:
      - grpc
      - grpcs
      - http
      - https
services:
  - connect_timeout: 60000
    enabled: true
    host: 127.0.0.1
    name: CORS
    tags: ["automation"]
    port: 80
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: CORS
        expression: http.method == "OPTIONS"
        preserve_host: false
        protocols:
          - http
          - https
        request_buffering: true
        response_buffering: true
        strip_path: false
    write_timeout: 60000
