profile:
  name: import
application:
  name: app-import
  version: 1.0.0
  platform: base
  fetch-descriptors: false
  port-start: 34000
  port-end: 34999
registry:
  url: https://folio-registry.dev.folio.org
install:
  folio: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/install.json
  eureka: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/eureka-platform.json
namespaces:
  platform-complete-ui: bkadirkhodjaev
environment:
  # PostgreSQL
  DB_HOST: postgres.eureka
  DB_PORT: 5432
  DB_DATABASE: folio
  DB_USERNAME: folio_rw
  DB_PASSWORD: supersecret
  DB_CHARSET: UTF-8
  DB_QUERYTIMEOUT: 60000
  DB_MAXPOOLSIZE: 4
  # Kafka
  ENV: folio
  KAFKA_HOST: kafka.eureka
  KAFKA_PORT: 9092
  KAFKA_PRODUCER_TENANT_COLLECTION: ALL
  # Kong
  KONG_ADMIN_URL: http://kong.eureka:8001
  KONG_INTEGRATION_ENABLED: "true"
  # Keycloak
  KC_URL: http://keycloak.eureka:8080
  KC_CONFIG_TTL: 3600s
  KC_ADMIN_CLIENT_ID: folio-backend-admin-client
  KC_ADMIN_CLIENT_SECRET: supersecret
  KC_ADMIN_USERNAME: admin
  KC_ADMIN_PASSWORD: admin
  KC_IMPORT_ENABLED: "true"
  KC_INTEGRATION_ENABLED: "true"
  KC_LOGIN_CLIENT_SUFFIX: -application
  KC_SERVICE_CLIENT_ID: sidecar-module-access-client
  KC_URI_VALIDATION_ENABLED: "false"
  SECURITY_ENABLED: "true"
  OKAPI_INTEGRATION_ENABLED: "false"
  WEB_CLIENT_TLS_VERIFY_HOSTNAME: "false"
  # Java
  JAVA_OPTIONS: >-
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
    -XX:MaxRAMPercentage=80.0 -Xms128m -Xmx400m 
    -Djdk.internal.httpclient.disableHostnameVerification=true
  # AWS S3/MinIO
  AWS_URL: http://minio.eureka:9000
  AWS_REGION: us-east-1
  AWS_BUCKET: example-bucket
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  S3_IS_AWS: false
  S3_URL: http://minio.eureka:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY_ID: minioadmin
  S3_SECRET_ACCESS_KEY: minioadmin
  S3_BUCKET: example-bucket
  SPLIT_FILES_ENABLED: true
tenants:
  diku:
    deploy-ui: true
roles:
  diku_admin_role:
    tenant: diku
    capability-sets: ["all"]
  diku_user_role:
    tenant: diku
    capability-sets: []
users:
  diku_admin:
    tenant: diku
    password: admin
    last-name: John
    first-name: Doe
    roles: ["diku_admin_role", "diku_user_role"]
  diku_user:
    tenant: diku
    password: user
    last-name: Jane
    first-name: Doe
    roles: ["diku_user_role"]
sidecar-module:
  image: folio-module-sidecar
  environment:
    # Kafka
    ENV: folio
    KAFKA_HOST: kafka.eureka
    KAFKA_PORT: 9092
    # Keycloak
    MOD_USERS_KEYCLOAK_URL: http://mod-users-keycloak-sc.eureka:8081
    # Management
    TM_CLIENT_URL: http://mgr-tenants.eureka:8081
    AM_CLIENT_URL: http://mgr-applications.eureka:8081
    TE_CLIENT_URL: http://mgr-tenant-entitlements.eureka:8081
    # Sidecar
    SIDECAR: "true"
    SIDECAR_FORWARD_UNKNOWN_REQUESTS: "true"
    SIDECAR_FORWARD_UNKNOWN_REQUESTS_DESTINATION: http://kong.eureka:8000
    QUARKUS_HTTP_PORT: 8081
    QUARKUS_REST_CLIENT_READ_TIMEOUT: 180000
    QUARKUS_REST_CLIENT_CONNECT_TIMEOUT: 180000
    QUARKUS_REST_CLIENT_SEND_TIMEOUT: 180000
    QUARKUS_HTTP_LIMITS_MAX_INITIAL_LINE_LENGTH: 8192
    SC_LOG_LEVEL: INFO
    ROOT_LOG_LEVEL: INFO
    REQUEST_TIMEOUT: 604800000
    ALLOW_CROSS_TENANT_REQUESTS: "true"
    # Java
    JAVA_OPTIONS: >-
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      -XX:+UseZGC -XX:MaxRAMPercentage=80.0 -Xms64m -Xmx64m
      -Dquarkus.http.host=0.0.0.0 -Dquarkus.log.level=INFO -Dquarkus.log.category.'org.apache.kafka'.level=INFO 
      -Djava.util.logging.manager=org.jboss.logmanager.LogManager
backend-modules:
  mgr-applications:
    port: 9901
    use-vault: true
    environment:
      MODULE_URL: http://mgr-applications.eureka:8081
      TE_URL: http://mgr-tenant-entitlements.eureka:8081
      VALIDATION_MODE: none
      ROUTEMANAGEMENT_ENABLE: "true"
      FOLIO_CLIENT_CONNECT_TIMEOUT: 600s
      FOLIO_CLIENT_READ_TIMEOUT: 600s
      KONG_CONNECT_TIMEOUT: "941241418"
      KONG_READ_TIMEOUT: "941241418"
      KONG_WRITE_TIMEOUT: "941241418"
    resources:
      cpus: 2
  mgr-tenants:
    port: 9902
    use-vault: true
    environment:
      MODULE_URL: http://mgr-tenants.eureka:8081
      FOLIO_CLIENT_CONNECT_TIMEOUT: 600s
      FOLIO_CLIENT_READ_TIMEOUT: 600s
      KONG_CONNECT_TIMEOUT: "941241418"
      KONG_READ_TIMEOUT: "941241418"
      KONG_WRITE_TIMEOUT: "941241418"
    resources:
      cpus: 2
  mgr-tenant-entitlements:
    port: 9903
    use-vault: true
    environment:
      MODULE_URL: http://mgr-tenant-entitlements.eureka:8081
      MT_CLIENT_URL: http://mgr-tenants.eureka:8081
      AM_CLIENT_URL: http://mgr-applications.eureka:8081
      VALIDATION_INTERFACE_INTEGRITY_ENTITLEMENT_ENABLED: "false"
      VALIDATION_INTERFACE_INTEGRITY_UPGRADE_ENABLED: "false"
      ROUTEMANAGEMENT_ENABLE: "false"
      FOLIO_CLIENT_CONNECT_TIMEOUT: 600s
      FOLIO_CLIENT_READ_TIMEOUT: 600s
      KONG_CONNECT_TIMEOUT: "941241418"
      KONG_READ_TIMEOUT: "941241418"
      KONG_WRITE_TIMEOUT: "941241418"
      FLOW_ENGINE_THREADS_NUM: "4"
      FLOW_ENGINE_MODULE_INSTALLER_THREADS: "2"
      RETRIES_MODULE_MAX: "10"
      KAFKA_ENTITLEMENT_TOPIC_PARTITIONS: "1"
      KAFKA_SCHEDULED_JOB_TOPIC_PARTITIONS: "1"
      KAFKA_CAPABILITY_TOPIC_PARTITIONS: "1"
      KAFKA_SYS_USER_TOPIC_PARTITIONS: "1"
      KAFKA_PRODUCER_TENANT_COLLECTION: "true"
      FLOW_ENGINE_PRINT_FLOW_RESULTS: "true"
    resources:
      cpus: 4
  mod-users-keycloak:
    use-vault: true
    use-okapi-url: true
    disable-system-user: true
    port: 9904
    environment:
      SINGLE_TENANT_UX: "false"
      INCLUDE_ONLY_VISIBLE_PERMISSIONS: "false"
      KAFKA_SYS_USER_TOPIC_RETRY_DELAY: 1s
      KAFKA_SYS_USER_TOPIC_RETRY_ATTEMPTS: "9223372036854775807"
      KAFKA_SYS_USER_CAPABILITIES_RETRY_DELAY: 5s
      KAFKA_SYS_USER_CAPABILITIES_RETRY_ATTEMPTS: "100"
    resources:
      cpus: 4
      memory: 900
  mod-login-keycloak:
    use-vault: true
    port: 9905
    environment:
      X_OKAPI_TOKEN_HEADER_ENABLED: "false"
      LOGIN_COOKIE_SAMESITE: "NONE"
      KC_ADMIN_TOKEN_TTL: 295s
  mod-roles-keycloak:
    use-vault: true
    disable-system-user: true
    port: 9906
    environment:
      CAPABILITY_TOPIC_RETRY_DELAY: 1s
      CAPABILITY_TOPIC_RETRY_ATTEMPTS: "9223372036854775807"
    resources:
      cpus: 4
  mod-scheduler:
    use-vault: true
    use-okapi-url: true
    disable-system-user: true
    port: 9907
    resources:
      cpus: 4
  mod-permissions:
  mod-configuration:
  mod-users:
  mod-roles:
  mod-password-validator:
  mod-settings:
  mod-notes:
  mod-tags:
  ### Inventory Modules
  mod-inventory-storage:
  mod-inventory:
    private-port: 9403
  mod-quick-marc:
  ### Data Import Modules
  mod-data-import:
  mod-di-converter-storage:
  mod-source-record-manager:
  mod-source-record-storage:
  mod-entities-links:
    disable-system-user: true
  mod-copycat:
  ### Data Export Modules
  mod-data-export:
  mod-data-export-spring:
    disable-system-user: true
  mod-data-export-worker:
  ### Acquisition Modules
  mod-orders-storage:
  mod-orders:
  mod-invoice-storage:
  mod-invoice:
  mod-organizations-storage:
  mod-organizations:
  mod-finance:
  mod-finance-storage:
    use-vault: true
  mod-audit:
    deploy-module: false
  ### Circulation Modules
  mod-circulation-storage:
    deploy-module: false
  mod-circulation:
    deploy-module: false
    private-port: 9801
  mod-pubsub:
    deploy-module: false
    disable-system-user: true
  # Search Module
  mod-search:
    deploy-module: false
    disable-system-user: true
    environment:
      ELASTICSEARCH_URL: http://opensearch.eureka:9200
frontend-modules:
  folio_data-import:
  folio_users:
  folio_tenant-settings:
  folio_inventory:
  folio_stripes-core:
  folio_developer:
  folio_notes:
  folio_tags:
  folio_organizations:
  folio_invoice:
  folio_orders:
  folio_quick-marc:
  folio_data-export:
  folio_stripes-smart-components:
  folio_plugin-find-instance:
  folio_plugin-find-user:
  folio_plugin-find-authority:
custom-frontend-modules:
  folio_authorization-roles:
    version: 2.1.109900000000214
  folio_authorization-policies:
    version: 2.0.109900000000102
  folio_plugin-select-application:
    version: 2.0.109900000000116
