_format_version: "3.0"
services:
  - connect_timeout: 60000
    enabled: true
    host: 127.0.0.1
    name: version
    tags: [ "automation" ]
    path: /
    plugins:
      - config:
          add:
            headers: []
            json: []
            json_types: []
          append:
            headers: []
            json: []
            json_types: []
          remove:
            headers: []
            json:
              - configuration
              - pids
              - timers
              - node_id
              - hostname
              - plugins
              - tagline
          rename:
            headers: []
          replace:
            headers: []
            json: []
            json_types: []
        enabled: true
        name: response-transformer
        protocols:
          - http
          - https
    port: 8001
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: version
        expression: http.method == "GET" && http.path == "/version"
