name: Build And Push UI

on:
  schedule:
    # Runs every day at 12:00 AM GMT+5 (7:00 AM UTC)
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      profile:
        description: "Deployment profile"
        required: true
        type: string
        default: combined
      namespace:
        description: "DockerHub namespace"
        required: true
        type: string
        default: bkadirkhodjaev
      tenant:
        description: "Tenant"
        required: true
        type: string
        default: diku
      platformCompleteURL:
        description: "Platform Complete UI url"
        required: true
        type: string
        default: http://localhost:3000
      singleTenant:
        description: "Use for Single Tenant workflow"
        required: true
        type: boolean
        default: true
      enableEcsRequests:
        description: "Enable ECS requests"
        required: true
        type: boolean
        default: false

jobs:
  build-ui:
    name: Build And Push UI
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_PROFILE: ${{ inputs.profile || 'combined' }}
      DOCKERHUB_NAMESPACE: ${{ inputs.namespace || 'bkadirkhodjaev' }}
      TENANT_NAME: ${{ inputs.tenant || 'diku' }}
      PLATFORM_COMPLETE_URL: ${{ inputs.platformCompleteURL || 'http://localhost:3000' }}
      SINGLE_TENANT_MODE: ${{ inputs.singleTenant || 'true' }}
      ENABLE_ECS_REQUESTS: ${{ inputs.enableEcsRequests || 'false' }}
    steps:
      - name: Using inputs
        run: |
          echo "profile: $DEPLOYMENT_PROFILE"
          echo "namespace: $DOCKERHUB_NAMESPACE"
          echo "tenant: $TENANT_NAME"
          echo "platformCompleteURL: $PLATFORM_COMPLETE_URL"
          echo "singleTenant: $SINGLE_TENANT_MODE"
          echo "enableEcsRequests: $ENABLE_ECS_REQUESTS"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_NAMESPACE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go Environment
        uses: ./.github/actions/setup-go

      - name: Prepare .eureka config directory
        run: |
          mkdir -p /home/runner/.eureka
          chmod -R 0700 /home/runner/.eureka

      - name: Build CLI
        working-directory: ./eureka-cli
        run: go build -o eureka-cli

      - name: Build And Push UI Command
        working-directory: ./eureka-cli
        run: |
          ./eureka-cli buildAndPushUi \
            --profile $DEPLOYMENT_PROFILE \
            --namespace $DOCKERHUB_NAMESPACE \
            --tenant $TENANT_NAME \
            --platformCompleteURL $PLATFORM_COMPLETE_URL \
            --singleTenant $SINGLE_TENANT_MODE \
            --enableEcsRequests $ENABLE_ECS_REQUESTS
          echo "Build And Push UI command ran successfully"
